### ISSUE TITLE
There seems to be something wrong with the resolution of the subselector

### ISSUE THREAD

**Issue by dombie** [jonkemp/css-rules#2]
Hi,
   There seems to be something wrong with the resolution of the subselector in css-rules.
Code sample:
```js
var parseCSS = require('css-rules');
var rules = parseCSS(`input[type="text"], div { color: red; font-size:132px}`);
console.log(rules[0][0]); // input[type='text'], div 
```
The group selectors are not separated.
I guess there's something wrong with the code.
```js
function extract(selectorText) {
    var attr = 0,
        sels = [],
        sel = '',
        i,
        c,
        l = selectorText.length;

    for (i = 0; i < l; i++) {
        c = selectorText.charAt(i);

        if (attr) {
            if (c === '[' || c === '(') { //  maybe ---->   if(c === ']' || c === ')') 
                attr--;
            }
            sel += c;
        } else if (c === ',') {
            sels.push(sel);
            sel = '';
        } else {
            if (c === '[' || c === '(') {
                attr++;
            }
            if (sel.length || (c !== ',' && c !== '\n' && c !== ' ')) {
                sel += c;
            }
        }
    }

    if (sel.length) {
        sels.push(sel);
    }

    return sels;
}
```
Looking forward to your reply.

**Comment by jonkemp** [comment]
This looks like a bug report. In order to be as helpful as possible, here are some guidelines for bug reports:

1. **Use the GitHub issue search** &mdash; check if the issue has already been reported.

2. **Check if the issue has been fixed** &mdash; try to reproduce it using the latest `master` or development branch in the repository.

3. **Isolate the problem** &mdash; create a [reduced test case](http://css-tricks.com/6263-reduced-test-cases/) and a live example.

A good bug report shouldn't leave others needing to chase you up for more information. Please try to be as detailed as possible in your report. What is your environment? What steps will reproduce the issue? What browser(s) and OS experience the problem? What would you expect to be the outcome? All these details will help people to fix any potential bugs. Thanks!
